version: '2.1'

services:
  composite-service:
    build: microservices/composite-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    build: api-gateway
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  user-service:
    build: microservices/user-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  eureka:
    build: eureka-server
    mem_limit: 350m



