server.port: 7000
server.error.include-message: always
spring.application.name: composite-service

app:
  eureka-username: u
  eureka-password: p
  eureka-server: localhost


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/springboot_realm
          jwk-set-uri: http://localhost:8081/auth/realms/springboot_realm/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

ribbon.ServerListRefreshInterval: 5000
ribbon.NFLoadBalancerPingInterval: 5

logging:
  level:
    root: INFO
    se.magnus: DEBUG

---

spring.profiles: docker

server.port: 8080

app:
  eureka-server: eureka